_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 2
                - 3
                - 35
                - 55
            "2":
                - 2
                - 3
                - 35
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 32
epochs:
    value: 10
hidden_layers:
    value:
        - 64
        - 64
        - 64
        - 64
learning_rate:
    value: 0.0006452648114254045
optimizer:
    value: sgd
trial_number:
    value: 4
weight_decay:
    value: 0.3643825583450049
weight_init:
    value: random
