wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hidden_layers:
  value:
  - 32
  - 32
  - 32
learning_rate:
  value: 0.0001
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
