wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hidden_layers:
  value:
  - 128
  - 128
  - 128
  - 128
  - 128
learning_rate:
  value: 0.001
optimizer:
  value: nag
weight_decay:
  value: 0.5
weight_init:
  value: random
