_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 35
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 16
epochs:
    value: 5
hidden_layers:
    value:
        - 32
        - 32
        - 32
learning_rate:
    value: 0.0005725635236446032
optimizer:
    value: sgd
trial_number:
    value: 30
weight_decay:
    value: 0.0007691386784789905
weight_init:
    value: xavier
