wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0005463696338677
optimizer:
  value: nag
weight_decay:
  value: 1.0453281609830778
weight_init:
  value: xavier
