wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.0004354628993664
optimizer:
  value: adam
weight_decay:
  value: 1.1863759798251827
weight_init:
  value: random
