wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 5
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.0005786316880874
optimizer:
  value: adam
weight_decay:
  value: 1.5756026966875132
weight_init:
  value: xavier
