wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.000387129199917
optimizer:
  value: sgd
weight_decay:
  value: 1.433995746066239
weight_init:
  value: random
