wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0006746032000096
optimizer:
  value: momentum
weight_decay:
  value: 1.080058061574218
weight_init:
  value: xavier
