wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
hidden_layers_type:
  value: small
learning_rate:
  value: 1.000378778978676
optimizer:
  value: rmsprop
weight_decay:
  value: 1.4147451468137664
weight_init:
  value: xavier
