wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0003077554054889
optimizer:
  value: rmsprop
weight_decay:
  value: 1.4396194021546431
weight_init:
  value: random
