wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0001427871154172
optimizer:
  value: momentum
weight_decay:
  value: 1.5198858496383665
weight_init:
  value: xavier
