wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0008517263371002
optimizer:
  value: sgd
weight_decay:
  value: 1.3142684811347949
weight_init:
  value: xavier
