wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.0003687785113111
optimizer:
  value: nadam
weight_decay:
  value: 1.1654197279223084
weight_init:
  value: xavier
