wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
hidden_layers_type:
  value: large
learning_rate:
  value: 1.000380573261776
optimizer:
  value: adam
weight_decay:
  value: 1.4849369892689956
weight_init:
  value: random
