wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.0009442441822394
optimizer:
  value: nag
weight_decay:
  value: 1.551443095977589
weight_init:
  value: xavier
