wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.0008796076016189
optimizer:
  value: momentum
weight_decay:
  value: 1.1251094478358898
weight_init:
  value: xavier
