wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0009348796259778
optimizer:
  value: adam
weight_decay:
  value: 1.443861710055644
weight_init:
  value: xavier
