wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.0004846512772
optimizer:
  value: rmsprop
weight_decay:
  value: 1.0689958845640952
weight_init:
  value: xavier
