wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
epochs:
  value: 5
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.0005477296571583
optimizer:
  value: adam
weight_decay:
  value: 1.6345943137855918
weight_init:
  value: random
