wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.0006075406795842
optimizer:
  value: momentum
weight_decay:
  value: 1.2440112480207943
weight_init:
  value: xavier
