wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0006460939731467
optimizer:
  value: adam
weight_decay:
  value: 1.057452469789426
weight_init:
  value: xavier
