wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 10
hidden_layers_type:
  value: large
learning_rate:
  value: 1.000724843209227
optimizer:
  value: nadam
weight_decay:
  value: 1.215881174283826
weight_init:
  value: xavier
