wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0004056730380633
optimizer:
  value: momentum
weight_decay:
  value: 1.3937203517239218
weight_init:
  value: xavier
