wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0009817145343096
optimizer:
  value: sgd
weight_decay:
  value: 1.097958323139678
weight_init:
  value: xavier
