wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0007572144800692
optimizer:
  value: rmsprop
weight_decay:
  value: 1.4995101752527895
weight_init:
  value: random
