wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layers_type:
  value: small
learning_rate:
  value: 1.0001786617309696
optimizer:
  value: nag
weight_decay:
  value: 1.087929359099141
weight_init:
  value: random
