wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_layers_type:
  value: large
learning_rate:
  value: 1.0008260150252248
optimizer:
  value: nadam
weight_decay:
  value: 1.4883478947983628
weight_init:
  value: xavier
