_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 2
                - 3
                - 5
                - 35
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: tanh
batch_size:
    value: 64
epochs:
    value: 10
hidden_layers:
    value:
        - 32
        - 32
        - 32
learning_rate:
    value: 0.00044291144678711164
optimizer:
    value: nadam
trial_number:
    value: 35
weight_decay:
    value: 0.00016230590269753932
weight_init:
    value: xavier
