_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 35
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 16
epochs:
    value: 5
hidden_layers:
    value:
        - 128
        - 128
        - 128
        - 128
        - 128
learning_rate:
    value: 0.000766390844018114
optimizer:
    value: momentum
trial_number:
    value: 0
weight_decay:
    value: 0.0006910123869940498
weight_init:
    value: random
