wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 10
hidden_layers_type:
  value: small
learning_rate:
  value: 1.0003502939018265
optimizer:
  value: momentum
weight_decay:
  value: 1.2512365128669949
weight_init:
  value: xavier
