wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
epochs:
  value: 10
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.000631330605071
optimizer:
  value: nag
weight_decay:
  value: 1.1988187647820574
weight_init:
  value: xavier
