wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers_type:
  value: medium
learning_rate:
  value: 1.0003842310155684
optimizer:
  value: momentum
weight_decay:
  value: 1.1712712478222769
weight_init:
  value: xavier
