_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 2
                - 3
                - 5
                - 35
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 35
                - 53
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 16
epochs:
    value: 5
hidden_layers_type:
    value: large
learning_rate:
    value: 0.0004137305229308512
optimizer:
    value: adam
weight_decay:
    value: 0.00011828729376021434
weight_init:
    value: xavier
