_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": linux-x86_64
activation:
    value: relu
batch_size:
    value: 64
epochs:
    value: 5
hidden_layers_type:
    value: large
learning_rate:
    value: 1.000530985398742
optimizer:
    value: nag
weight_decay:
    value: 1.183843251846313
weight_init:
    value: xavier
