wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_layers_type:
  value: small
learning_rate:
  value: 1.000437788219814
optimizer:
  value: nag
weight_decay:
  value: 1.488666087890543
weight_init:
  value: xavier
